-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 16:05:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GWASdb_v0
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GWASdb_v0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GWASdb_v0` DEFAULT CHARACTER SET utf8 ;
USE `GWASdb_v0` ;

-- -----------------------------------------------------
-- Table `GWASdb_v0`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`species` (
  `species_id` SMALLINT(3) UNSIGNED NOT NULL,
  `shortname` VARCHAR(45) NOT NULL,
  `binomial` VARCHAR(45) NOT NULL,
  `subspecies` VARCHAR(45) NULL,
  `variety` VARCHAR(45) NULL,
  PRIMARY KEY (`species_id`),
  UNIQUE INDEX `species_id_UNIQUE` (`species_id` ASC),
  UNIQUE INDEX `shortname_UNIQUE` (`shortname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`population`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`population` (
  `population_id` SMALLINT(3) UNSIGNED NOT NULL,
  `population_name` VARCHAR(100) NOT NULL,
  `population_species` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`population_id`),
  UNIQUE INDEX `population_id_UNIQUE` (`population_id` ASC),
  INDEX `species_id_idx` (`population_species` ASC),
  CONSTRAINT `population_species_species_id`
    FOREIGN KEY (`population_species`)
    REFERENCES `GWASdb_v0`.`species` (`species_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`growout_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`growout_type` (
  `growout_type_id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `growout_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`growout_type_id`),
  UNIQUE INDEX `growout_type_id_UNIQUE` (`growout_type_id` ASC),
  UNIQUE INDEX `growout_type_UNIQUE` (`growout_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`growout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`growout` (
  `growout_id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `growout_name` VARCHAR(75) NOT NULL,
  `growout_population` SMALLINT(3) UNSIGNED NOT NULL,
  `location_country` VARCHAR(45) NULL,
  `location_state` VARCHAR(45) NULL,
  `location_city` VARCHAR(45) NULL,
  `year` YEAR NOT NULL,
  `growout_growout_type` TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`growout_id`),
  UNIQUE INDEX `growout_id_UNIQUE` (`growout_id` ASC),
  UNIQUE INDEX `growout_name_UNIQUE` (`growout_name` ASC),
  INDEX `growout_growout_type_idx` (`growout_growout_type` ASC),
  INDEX `growout_population_idx` (`growout_population` ASC),
  CONSTRAINT `growout_growout_type_growout_type_id`
    FOREIGN KEY (`growout_growout_type`)
    REFERENCES `GWASdb_v0`.`growout_type` (`growout_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `growout_population_population_id`
    FOREIGN KEY (`growout_population`)
    REFERENCES `GWASdb_v0`.`population` (`population_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`line` (
  `line_id` SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `line_name` VARCHAR(45) NOT NULL,
  `line_population` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`line_id`),
  UNIQUE INDEX `line_id_UNIQUE` (`line_id` ASC),
  INDEX `population_population_id_idx` (`line_population` ASC),
  UNIQUE INDEX `line_name_UNIQUE` (`line_name` ASC),
  CONSTRAINT `line_population_population_id`
    FOREIGN KEY (`line_population`)
    REFERENCES `GWASdb_v0`.`population` (`population_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`sample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`sample` (
  `sample_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sample_name` VARCHAR(45) NOT NULL,
  `sample_growout` SMALLINT(3) UNSIGNED NOT NULL,
  `sample_line` SMALLINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`sample_id`),
  UNIQUE INDEX `sample_id_UNIQUE` (`sample_id` ASC),
  INDEX `line_line_id_idx` (`sample_line` ASC),
  INDEX `growout_growout_id_idx` (`sample_growout` ASC),
  CONSTRAINT `sample_line_line_id`
    FOREIGN KEY (`sample_line`)
    REFERENCES `GWASdb_v0`.`line` (`line_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sample_growout_growout_id`
    FOREIGN KEY (`sample_growout`)
    REFERENCES `GWASdb_v0`.`growout` (`growout_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`chromosome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`chromosome` (
  `chromosome_id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chromosome_species` SMALLINT(3) UNSIGNED NOT NULL,
  `chromosome_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`chromosome_id`),
  UNIQUE INDEX `chromosome_id_UNIQUE` (`chromosome_id` ASC),
  INDEX `species_species_id_idx` (`chromosome_species` ASC),
  CONSTRAINT `chromosome_species_species_id`
    FOREIGN KEY (`chromosome_species`)
    REFERENCES `GWASdb_v0`.`species` (`species_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`nucleotide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`nucleotide` (
  `nucleotide_id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `iupac_nucleotide_code` VARCHAR(10) NOT NULL,
  `base` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`nucleotide_id`),
  UNIQUE INDEX `nucleotide_id_UNIQUE` (`nucleotide_id` ASC),
  UNIQUE INDEX `iupac_nucleotide_code_UNIQUE` (`iupac_nucleotide_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`genotype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`genotype` (
  `genotype_id` BIGINT(15) UNSIGNED NOT NULL AUTO_INCREMENT,
  `genotype_line` SMALLINT(4) UNSIGNED NOT NULL,
  `genotype_chromosome` SMALLINT(3) UNSIGNED NOT NULL,
  `position` INT UNSIGNED NOT NULL,
  `genotype_nucleotide` TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`genotype_id`),
  UNIQUE INDEX `genotype_id_UNIQUE` (`genotype_id` ASC),
  INDEX `line_line_id_idx` (`genotype_line` ASC),
  INDEX `chromosome_chromosome_id_idx` (`genotype_chromosome` ASC),
  INDEX `nucleotide_nucleotide_id_idx` (`genotype_nucleotide` ASC),
  CONSTRAINT `genotype_line_line_id`
    FOREIGN KEY (`genotype_line`)
    REFERENCES `GWASdb_v0`.`line` (`line_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genotype_chromosome_chromosome_id`
    FOREIGN KEY (`genotype_chromosome`)
    REFERENCES `GWASdb_v0`.`chromosome` (`chromosome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genotype_nucleotide_nucleotide_id`
    FOREIGN KEY (`genotype_nucleotide`)
    REFERENCES `GWASdb_v0`.`nucleotide` (`nucleotide_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`trait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`trait` (
  `trait_id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `trait_name` VARCHAR(45) NOT NULL,
  `measurement_unit` VARCHAR(45) NULL,
  `measurement_device` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`trait_id`),
  UNIQUE INDEX `trait_id_UNIQUE` (`trait_id` ASC),
  UNIQUE INDEX `trait_name_UNIQUE` (`trait_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`phenotype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`phenotype` (
  `phenotype_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phenotype_sample` INT UNSIGNED NOT NULL,
  `phenotype_trait` SMALLINT(3) UNSIGNED NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`phenotype_id`),
  UNIQUE INDEX `phenotype_id_UNIQUE` (`phenotype_id` ASC),
  INDEX `sample_sample_id_idx` (`phenotype_sample` ASC),
  INDEX `trait_trait_id_idx` (`phenotype_trait` ASC),
  CONSTRAINT `phenotype_sample_sample_id`
    FOREIGN KEY (`phenotype_sample`)
    REFERENCES `GWASdb_v0`.`sample` (`sample_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `phenotype_trait_trait_id`
    FOREIGN KEY (`phenotype_trait`)
    REFERENCES `GWASdb_v0`.`trait` (`trait_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`reference_genotype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`reference_genotype` (
  `reference_genotype_id` INT NOT NULL,
  `reference_genotype_name` VARCHAR(45) NULL,
  `reference_genotype_species` VARCHAR(45) NULL,
  `reference_genotype_chromosome` VARCHAR(45) NULL,
  `reference_genotype_position` VARCHAR(45) NULL,
  `reference_genotype_nucleotide` VARCHAR(45) NULL,
  PRIMARY KEY (`reference_genotype_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`gwas_algorithm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`gwas_algorithm` (
  `GWAS_algorithm_id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `GWAS_algorithm_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GWAS_algorithm_id`),
  UNIQUE INDEX `GWAS_algorithm_id_UNIQUE` (`GWAS_algorithm_id` ASC),
  UNIQUE INDEX `GWAS_algorithm_name_UNIQUE` (`GWAS_algorithm_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`kinship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`kinship` (
  `kinship_id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `kinship_calculation_method` VARCHAR(45) NULL,
  `kinship_matrix_storage_loc` VARCHAR(45) NULL,
  PRIMARY KEY (`kinship_id`),
  UNIQUE INDEX `kinship_id_UNIQUE` (`kinship_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`imputation_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`imputation_method` (
  `imputation_method_id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `imputation_method_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`imputation_method_id`),
  UNIQUE INDEX `imputation_method_id_UNIQUE` (`imputation_method_id` ASC),
  UNIQUE INDEX `imputation_method_name_UNIQUE` (`imputation_method_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`population_structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`population_structure` (
  `population_structure_id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `population_structure_calculation_method` VARCHAR(45) NULL,
  `population_structure_storage_loc` VARCHAR(45) NULL,
  PRIMARY KEY (`population_structure_id`),
  UNIQUE INDEX `population_structure_id_UNIQUE` (`population_structure_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`gwas_run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`gwas_run` (
  `GWAS_run_id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gwas_algorithm` TINYINT(2) UNSIGNED NOT NULL,
  `missing_snp_cutoff_value` DECIMAL(5,4) NOT NULL,
  `missing_line_cutoff_value` DECIMAL(5,4) NOT NULL,
  `gwas_run_imputation_method` TINYINT(2) UNSIGNED NOT NULL,
  `gwas_run_kinship` SMALLINT(3) UNSIGNED NOT NULL,
  `gwas_run_population_structure` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`GWAS_run_id`),
  UNIQUE INDEX `GWAS_run_id_UNIQUE` (`GWAS_run_id` ASC),
  INDEX `gwas_algorithm_gwas_algorithm_id_idx` (`gwas_algorithm` ASC),
  INDEX `gwas_run_kinship_kinship_id_idx` (`gwas_run_kinship` ASC),
  INDEX `imputation_method_imputation_method_id_idx` (`gwas_run_imputation_method` ASC),
  INDEX `gwas_run_population_structure_population_structure_id_idx` (`gwas_run_population_structure` ASC),
  CONSTRAINT `gwas_run_gwas_algorithm_gwas_algorithm_id`
    FOREIGN KEY (`gwas_algorithm`)
    REFERENCES `GWASdb_v0`.`gwas_algorithm` (`GWAS_algorithm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gwas_run_kinship_kinship_id`
    FOREIGN KEY (`gwas_run_kinship`)
    REFERENCES `GWASdb_v0`.`kinship` (`kinship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gwas_run_imputation_method_imputation_method_id`
    FOREIGN KEY (`gwas_run_imputation_method`)
    REFERENCES `GWASdb_v0`.`imputation_method` (`imputation_method_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gwas_run_population_structure_population_structure_id`
    FOREIGN KEY (`gwas_run_population_structure`)
    REFERENCES `GWASdb_v0`.`population_structure` (`population_structure_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GWASdb_v0`.`gwas_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GWASdb_v0`.`gwas_result` (
  `gwas_result_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gwas_result_chromosome` SMALLINT(3) UNSIGNED NOT NULL,
  `basepair` INT UNSIGNED NOT NULL,
  `gwas_result_trait` SMALLINT(3) UNSIGNED NOT NULL,
  `snp` DOUBLE(15,10) NULL,
  `logp` DOUBLE(25,20) NULL,
  `null_logp` DOUBLE(25,20) NULL,
  `cofactor` TINYINT(2) UNSIGNED NULL,
  `order` TINYINT(3) UNSIGNED NULL,
  `gwas_result_gwas_run` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`gwas_result_id`),
  UNIQUE INDEX `gwas_result_id_UNIQUE` (`gwas_result_id` ASC),
  INDEX `chromosome_chromosome_id_idx` (`gwas_result_chromosome` ASC),
  INDEX `trait_trait_id_idx` (`gwas_result_trait` ASC),
  INDEX `gwas_run_gwas_run_id_idx` (`gwas_result_gwas_run` ASC),
  CONSTRAINT `gwas_result_chromosome_chromosome_id`
    FOREIGN KEY (`gwas_result_chromosome`)
    REFERENCES `GWASdb_v0`.`chromosome` (`chromosome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gwas_result_trait_trait_id`
    FOREIGN KEY (`gwas_result_trait`)
    REFERENCES `GWASdb_v0`.`trait` (`trait_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gwas_result_gwas_run_gwas_run_id`
    FOREIGN KEY (`gwas_result_gwas_run`)
    REFERENCES `GWASdb_v0`.`gwas_run` (`GWAS_run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
